In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [2]:
dataset = pd.read_csv('Churn_Modelling.csv')
dataset

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [3]:
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, -1].values

In [4]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [5]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [6]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:,2])
X[:, 2]

array([0, 0, 0, ..., 0, 1, 0], dtype=object)

In [7]:
X[:, 1]

array(['France', 'Spain', 'France', ..., 'France', 'Germany', 'France'],
      dtype=object)

In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [1])], remainder = 'passthrough')
X = np.array(ct.fit_transform(X))
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [10]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [11]:
X_train

array([[-1.01460667, -0.5698444 ,  1.74309049, ...,  0.64259497,
        -1.03227043,  1.10643166],
       [-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
         0.9687384 , -0.74866447],
       [ 0.98560362, -0.5698444 , -0.57369368, ...,  0.64259497,
        -1.03227043,  1.48533467],
       ...,
       [ 0.98560362, -0.5698444 , -0.57369368, ...,  0.64259497,
        -1.03227043,  1.41231994],
       [-1.01460667, -0.5698444 ,  1.74309049, ...,  0.64259497,
         0.9687384 ,  0.84432121],
       [-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
        -1.03227043,  0.32472465]])

## ANN

In [12]:
ann = tf.keras.models.Sequential()

## Input layer and 1st hidden layer

In [13]:
ann.add(tf.keras.layers.Dense(units = 6, activation='relu'))

## 2nd hidden layer

In [14]:
ann.add(tf.keras.layers.Dense(units = 6, activation='relu'))

## Output Layer

In [15]:
ann.add(tf.keras.layers.Dense(units = 1, activation='sigmoid'))

## Compiling ANN

In [16]:
ann.compile(optimizer='adam' , loss='binary_crossentropy' , metrics=['accuracy'])

## Training the ANN

In [17]:
ann.fit(X_train, y_train, batch_size=32, epochs=100)

Train on 8000 samples
Epoch 1/100
8000/8000 [==============================] - 3s 314us/sample - loss: 0.5371 - accuracy: 0.7673
Epoch 2/100
8000/8000 [==============================] - 1s 78us/sample - loss: 0.4591 - accuracy: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 64us/sample - loss: 0.4369 - accuracy: 0.8021
Epoch 4/100
8000/8000 [==============================] - 1s 78us/sample - loss: 0.4274 - accuracy: 0.8144
Epoch 5/100
8000/8000 [==============================] - 1s 104us/sample - loss: 0.4221 - accuracy: 0.8195
Epoch 6/100
8000/8000 [==============================] - 1s 80us/sample - loss: 0.4174 - accuracy: 0.8229
Epoch 7/100
8000/8000 [==============================] - 1s 77us/sample - loss: 0.4140 - accuracy: 0.8248
Epoch 8/100
8000/8000 [==============================] - 1s 72us/sample - loss: 0.4105 - accuracy: 0.8266
Epoch 9/100
8000/8000 [==============================] - 1s 72us/sample - loss: 0.4074 - accuracy: 0.8280
Epoch 10/100
8000/8000

8000/8000 [==============================] - 1s 74us/sample - loss: 0.3426 - accuracy: 0.8586
Epoch 78/100
8000/8000 [==============================] - 1s 70us/sample - loss: 0.3420 - accuracy: 0.8612
Epoch 79/100
8000/8000 [==============================] - 1s 64us/sample - loss: 0.3424 - accuracy: 0.8594
Epoch 80/100
8000/8000 [==============================] - 1s 64us/sample - loss: 0.3419 - accuracy: 0.8594
Epoch 81/100
8000/8000 [==============================] - 1s 69us/sample - loss: 0.3417 - accuracy: 0.8611
Epoch 82/100
8000/8000 [==============================] - 1s 71us/sample - loss: 0.3418 - accuracy: 0.8584
Epoch 83/100
8000/8000 [==============================] - 1s 69us/sample - loss: 0.3415 - accuracy: 0.8608
Epoch 84/100
8000/8000 [==============================] - 1s 70us/sample - loss: 0.3420 - accuracy: 0.8590
Epoch 85/100
8000/8000 [==============================] - 1s 69us/sample - loss: 0.3412 - accuracy: 0.8599
Epoch 86/100
8000/8000 [==========================

## Make predictions and evaluating the model

In [18]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000 ]])) > 0.5)

[[False]]


## Predicting Test Results

In [19]:
y_pred = ann.predict(X_test)
y_pred = (y_pred>0.5)
np.set_printoptions(precision = 2)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


## Confusion Matrix

In [20]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1510   85]
 [ 201  204]]


In [21]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.857